unset HBASE_HOME
unset HBASE_CONF_DIR
unset HADOOP_HOME
unset HADOOP_CONF_DIR
unset HADOOP_CLASSPATH

export HBASE_HOME
export HBASE_CONF_DIR
export HADOOP_HOME
export HADOOP_CONF_DIR
export HADOOP_CLASSPATH

./drill-embedded
